services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongoDB:/data/db
    networks:
      - webapp-network
  app:
    image: thomasy2022/candidate_express_app
    environment: 
      - DATABASE_CONNECTIONSTRING=mongodb://mongo:27017
    depends_on:
      - mongo
    ports:
      - 4000:4000
    networks:
      - webapp-network
networks:
  webapp-network:
    driver: bridge      
volumes:
  mongoDB: {}